-- ============================================================
-- COVIAR 3.0 - MIGRACIÓN A POSTGRESQL LOCAL
-- Archivo 2 de 2: IMPORTACIÓN DE DATOS (vía COPY)
--
-- IMPORTANTE: Ejecutar como superusuario (postgres), NO como coviar_user.
-- El comando COPY necesita acceso al filesystem del servidor.
--
-- Prerequisito: haber ejecutado coviar_migration_1_schema.sql primero.
-- ============================================================

-- ============================================================
-- PASO 1: Cambiar IDENTITY a BY DEFAULT para permitir IDs explícitos
-- ============================================================
ALTER TABLE provincias             ALTER COLUMN id_provincia             SET GENERATED BY DEFAULT;
ALTER TABLE departamentos          ALTER COLUMN id_departamento          SET GENERATED BY DEFAULT;
ALTER TABLE localidades            ALTER COLUMN id_localidad             SET GENERATED BY DEFAULT;
ALTER TABLE segmentos              ALTER COLUMN id_segmento              SET GENERATED BY DEFAULT;
ALTER TABLE niveles_sostenibilidad ALTER COLUMN id_nivel_sostenibilidad  SET GENERATED BY DEFAULT;
ALTER TABLE capitulos              ALTER COLUMN id_capitulo              SET GENERATED BY DEFAULT;
ALTER TABLE indicadores            ALTER COLUMN id_indicador             SET GENERATED BY DEFAULT;
ALTER TABLE niveles_respuesta      ALTER COLUMN id_nivel_respuesta       SET GENERATED BY DEFAULT;
ALTER TABLE bodegas                ALTER COLUMN id_bodega                SET GENERATED BY DEFAULT;
ALTER TABLE cuentas                ALTER COLUMN id_cuenta                SET GENERATED BY DEFAULT;
ALTER TABLE responsables           ALTER COLUMN id_responsable           SET GENERATED BY DEFAULT;
ALTER TABLE autoevaluaciones       ALTER COLUMN id_autoevaluacion        SET GENERATED BY DEFAULT;
ALTER TABLE respuestas             ALTER COLUMN id_respuesta             SET GENERATED BY DEFAULT;
ALTER TABLE evidencias             ALTER COLUMN id_evidencia             SET GENERATED BY DEFAULT;

-- ============================================================
-- PASO 2: Importar datos desde CSV
-- (columna vacía en CSV = NULL gracias a NULL '')
-- ============================================================

COPY provincias (id_provincia, nombre)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/provincias_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY departamentos (id_departamento, nombre, id_provincia)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/departamentos_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY localidades (id_localidad, nombre, id_departamento)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/localidades_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY segmentos (id_segmento, nombre, min_turistas, max_turistas)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/segmentos_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY niveles_sostenibilidad (id_nivel_sostenibilidad, id_segmento, nombre, min_puntaje, max_puntaje)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/niveles_sostenibilidad_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY capitulos (id_capitulo, nombre, descripcion, orden)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/capitulos_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY indicadores (id_indicador, id_capitulo, nombre, descripcion, orden)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/indicadores_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY niveles_respuesta (id_nivel_respuesta, id_indicador, nombre, descripcion, puntos, posicion)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/niveles_respuesta_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY bodegas (id_bodega, razon_social, nombre_fantasia, cuit, inv_bod, inv_vin,
              calle, numeracion, id_localidad, telefono, email_institucional, fecha_registro)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/bodegas_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY cuentas (id_cuenta, tipo, id_bodega, email_login, password_hash, fecha_registro)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/cuentas_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY responsables (id_responsable, id_cuenta, nombre, apellido, cargo, dni,
                   activo, fecha_registro, fecha_baja)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/responsables_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY autoevaluaciones (id_autoevaluacion, fecha_inicio, fecha_fin, estado,
                       id_bodega, id_segmento, puntaje_final,
                       id_nivel_sostenibilidad, estado_evidencia)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/autoevaluaciones_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY respuestas (id_respuesta, id_nivel_respuesta, id_indicador, id_autoevaluacion)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/respuestas_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY segmento_indicador (id_segmento, id_indicador)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/segmento_indicador_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

COPY evidencias (id_evidencia, id_respuesta, nombre, ubicacion)
FROM 'C:/Users/Carlii/Desktop/CoviarGO/Coviar 3.0 (PostgreLocal)/CSV_BD/evidencias_rows.csv'
WITH (FORMAT CSV, HEADER true, NULL '');

-- ============================================================
-- PASO 3: Restaurar IDENTITY a GENERATED ALWAYS
-- ============================================================
ALTER TABLE provincias             ALTER COLUMN id_provincia             SET GENERATED ALWAYS;
ALTER TABLE departamentos          ALTER COLUMN id_departamento          SET GENERATED ALWAYS;
ALTER TABLE localidades            ALTER COLUMN id_localidad             SET GENERATED ALWAYS;
ALTER TABLE segmentos              ALTER COLUMN id_segmento              SET GENERATED ALWAYS;
ALTER TABLE niveles_sostenibilidad ALTER COLUMN id_nivel_sostenibilidad  SET GENERATED ALWAYS;
ALTER TABLE capitulos              ALTER COLUMN id_capitulo              SET GENERATED ALWAYS;
ALTER TABLE indicadores            ALTER COLUMN id_indicador             SET GENERATED ALWAYS;
ALTER TABLE niveles_respuesta      ALTER COLUMN id_nivel_respuesta       SET GENERATED ALWAYS;
ALTER TABLE bodegas                ALTER COLUMN id_bodega                SET GENERATED ALWAYS;
ALTER TABLE cuentas                ALTER COLUMN id_cuenta                SET GENERATED ALWAYS;
ALTER TABLE responsables           ALTER COLUMN id_responsable           SET GENERATED ALWAYS;
ALTER TABLE autoevaluaciones       ALTER COLUMN id_autoevaluacion        SET GENERATED ALWAYS;
ALTER TABLE respuestas             ALTER COLUMN id_respuesta             SET GENERATED ALWAYS;
ALTER TABLE evidencias             ALTER COLUMN id_evidencia             SET GENERATED ALWAYS;

-- ============================================================
-- PASO 4: Resetear secuencias para que nuevos registros no colisionen
-- ============================================================
SELECT setval(pg_get_serial_sequence('provincias',             'id_provincia'),
              (SELECT MAX(id_provincia)             FROM provincias));

SELECT setval(pg_get_serial_sequence('departamentos',          'id_departamento'),
              (SELECT MAX(id_departamento)          FROM departamentos));

SELECT setval(pg_get_serial_sequence('localidades',            'id_localidad'),
              (SELECT MAX(id_localidad)             FROM localidades));

SELECT setval(pg_get_serial_sequence('segmentos',              'id_segmento'),
              (SELECT MAX(id_segmento)              FROM segmentos));

SELECT setval(pg_get_serial_sequence('niveles_sostenibilidad', 'id_nivel_sostenibilidad'),
              (SELECT MAX(id_nivel_sostenibilidad)  FROM niveles_sostenibilidad));

SELECT setval(pg_get_serial_sequence('capitulos',              'id_capitulo'),
              (SELECT MAX(id_capitulo)              FROM capitulos));

SELECT setval(pg_get_serial_sequence('indicadores',            'id_indicador'),
              (SELECT MAX(id_indicador)             FROM indicadores));

SELECT setval(pg_get_serial_sequence('niveles_respuesta',      'id_nivel_respuesta'),
              (SELECT MAX(id_nivel_respuesta)       FROM niveles_respuesta));

SELECT setval(pg_get_serial_sequence('bodegas',                'id_bodega'),
              (SELECT MAX(id_bodega)                FROM bodegas));

SELECT setval(pg_get_serial_sequence('cuentas',                'id_cuenta'),
              (SELECT MAX(id_cuenta)                FROM cuentas));

SELECT setval(pg_get_serial_sequence('responsables',           'id_responsable'),
              (SELECT MAX(id_responsable)           FROM responsables));

SELECT setval(pg_get_serial_sequence('autoevaluaciones',       'id_autoevaluacion'),
              (SELECT MAX(id_autoevaluacion)        FROM autoevaluaciones));

SELECT setval(pg_get_serial_sequence('respuestas',             'id_respuesta'),
              (SELECT MAX(id_respuesta)             FROM respuestas));

SELECT setval(pg_get_serial_sequence('evidencias',             'id_evidencia'),
              (SELECT MAX(id_evidencia)             FROM evidencias));

SELECT setval('password_reset_tokens_id_seq',
              COALESCE((SELECT MAX(id) FROM restaurar_contrasenas), 1));
